#include "led_cfg.h"
#include "private.h"

LedCfg_t ledCfg[NUM_OF_LEDS] = {
	{PORTA_PIN_0, PIN_OUTPUT},
	{PORTA_PIN_1, PIN_OUTPUT},
	{PORTA_PIN_2, PIN_OUTPUT},
	{PORTA_PIN_3, PIN_OUTPUT},
	{PORTA_PIN_4, PIN_OUTPUT},
	{PORTA_PIN_5, PIN_OUTPUT},
	{PORTA_PIN_6, PIN_OUTPUT},
	{PORTA_PIN_7, PIN_OUTPUT},

	// port B
	{PORTB_PIN_0, PIN_OUTPUT},
	{PORTB_PIN_1, PIN_OUTPUT},
	{PORTB_PIN_2, PIN_OUTPUT},
	{PORTB_PIN_3, PIN_OUTPUT},
	{PORTB_PIN_4, PIN_OUTPUT},
	{PORTB_PIN_5, PIN_OUTPUT},
	{PORTB_PIN_6, PIN_OUTPUT},
	{PORTB_PIN_7, PIN_OUTPUT},

	// port C
	{PORTC_PIN_0, PIN_OUTPUT},
	{PORTC_PIN_1, PIN_OUTPUT},
	{PORTC_PIN_2, PIN_OUTPUT},
	{PORTC_PIN_3, PIN_OUTPUT},
	{PORTC_PIN_4, PIN_OUTPUT},
	{PORTC_PIN_5, PIN_OUTPUT},
	{PORTC_PIN_6, PIN_OUTPUT},
	{PORTC_PIN_7, PIN_OUTPUT},

	// port D
	{PORTD_PIN_0, PIN_OUTPUT},
	{PORTD_PIN_1, PIN_OUTPUT},
	{PORTD_PIN_2, PIN_OUTPUT},
	{PORTD_PIN_3, PIN_OUTPUT},
	{PORTD_PIN_4, PIN_OUTPUT},
	{PORTD_PIN_5, PIN_OUTPUT},
	{PORTD_PIN_6, PIN_OUTPUT},
	{PORTD_PIN_7, PIN_OUTPUT}

};
