#include "Switch_cfg.h"
#include "private.h"

SwitchCfg_t switchCfg[NUM_OF_SWITCHES] = {
	// PORTA switches
	{PORTA_PIN_0, PIN_INPUT},
	//{PORTA_PIN_1, PIN_INPUT},
	{PORTA_PIN_2, PIN_INPUT},
	{PORTA_PIN_3, PIN_INPUT},
	{PORTA_PIN_4, PIN_INPUT},
	{PORTA_PIN_5, PIN_INPUT},
	{PORTA_PIN_6, PIN_INPUT},
	{PORTA_PIN_7, PIN_INPUT},

	// PORTB switches
	{PORTB_PIN_0, PIN_INPUT},
	{PORTB_PIN_1, PIN_INPUT},
	{PORTB_PIN_2, PIN_INPUT},
	{PORTB_PIN_3, PIN_INPUT},
	{PORTB_PIN_4, PIN_INPUT},
	{PORTB_PIN_5, PIN_INPUT},
	{PORTB_PIN_6, PIN_INPUT},
	{PORTB_PIN_7, PIN_INPUT},

	// PORTC switches
	{PORTC_PIN_0, PIN_INPUT},
	{PORTC_PIN_1, PIN_INPUT},
	{PORTC_PIN_2, PIN_INPUT},
	{PORTC_PIN_3, PIN_INPUT},
	{PORTC_PIN_4, PIN_INPUT},
	{PORTC_PIN_5, PIN_INPUT},
	{PORTC_PIN_6, PIN_INPUT},
	{PORTC_PIN_7, PIN_INPUT},

	// PORTD switches
	{PORTD_PIN_0, PIN_INPUT},
	{PORTD_PIN_1, PIN_INPUT},
	{PORTD_PIN_2, PIN_INPUT},
	{PORTD_PIN_3, PIN_INPUT},
	{PORTD_PIN_4, PIN_INPUT},
	{PORTD_PIN_5, PIN_INPUT},
	{PORTD_PIN_6, PIN_INPUT},
	{PORTD_PIN_7, PIN_INPUT}
};
